trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository

steps:
  # Optional: Ensure .m2/repository exists before trying to cache it
  - script: mkdir -p $(MAVEN_CACHE_FOLDER)
    displayName: 'Create Maven cache directory'


  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
      path: $(MAVEN_CACHE_FOLDER)
    continueOnError: true

  - task: Maven@4
    inputs:
      azureSubscription: 'Azure subscription 1(d21bd131-a869-4493-98ac-685d6c8b1d58)'
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
  
  - task: Docker@2
    inputs:
     containerRegistry: 'test1'
     repository: 'abc'
     command: 'buildAndPush'
     Dockerfile: '**/Dockerfile'

  - task: Kubernetes@1
    inputs:
         connectionType: 'Kubernetes Service Connection'
         kubernetesServiceEndpoint: 'abc'
         namespace: 'default'
         command: 'apply'
         useConfigurationFile: true
         configuration: 'deployment.yaml'
         secretType: 'dockerRegistry'
         containerRegistryType: 'Azure Container Registry'